# Generated by Django 4.2.11 on 2025-03-27 06:42

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('libraries', '0002_alter_book_author_alter_book_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='customerrating',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default=django.utils.timezone.now, max_length=13, validators=[django.core.validators.MinLengthValidator(13)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='salespoint',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
